networks:
  chatnetwork:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6376:6379
    networks:
      - chatnetwork

  go_backend:
    build: .
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - chatnetwork

  frontend:
    build: ./redchat-frontend
    depends_on:
      - go_backend
    ports:
      - 8081:4173
    networks:
      - chatnetwork
    volumes:
      - ./redchat-frontend/dist:/usr/share/caddy/html
      - ./redchat-frontend/Caddyfile:/etc/caddy/Caddyfile
